### ISSUE TITLE
task manager and file manager 

### ISSUE THREAD

**Issue by mandoof1** [arsium/HorusEyesRat_Public#2]
task manager and file manager  completely not working and iam not sure if its a me problem or just the rat problem

**Comment by arsium** [comment]
No one reports an issue like that. This is quite strange

**Comment by mandoof1** [comment]
Do u have a discord or some way for me to contact u so I can show u the issue??

**Comment by mandoof1** [comment]
> 
> 
> No one reports an issue like that. This is quite strange

Do u have a discord or some way for me to contact u so I can show u the issue??

**Comment by mandoof1** [comment]
anyone having this issue just right click and refresh for some reason it wont work for me until i refresh

**Comment by arsium** [comment]
Yes you need to refresh it is shown in the video
